function [error_train, error_val] = ...
    learningCurve(input_layer_size, ...
                            hidden_layer_size, ...
                            num_labels, ...
							options, ...
							X, y, Xval, yval, lambda)
m = size(X, 1);
error_train = zeros(m, 1);
error_val   = zeros(m, 1);
	for i = 1:m
		[nn_params] = trainNN(input_layer_size, ...
									hidden_layer_size, ...
									num_labels, ...
									options, ...
									X(1:i, :), y(1:i), lambda);
		error_train(i) = nnCostFunction(nn_params, ...
                                   input_layer_size, ...
                                   hidden_layer_size, ...
                                   num_labels, ...
                                   X(1:i, :), y(1:i), 0);
		error_val(i) = nnCostFunction(nn_params, ...
                                   input_layer_size, ...
                                   hidden_layer_size, ...
                                   num_labels, ...
                                   Xval, yval, 0);
	end
end
