function [lambda_vec, error_train, error_val] = ...
    validationCurve(input_layer_size, ...
                            hidden_layer_size, ...
                            num_labels, ...
							options, ...
							X, y, Xval, yval)
	lambda_vec = [100 1000 10000]';
	error_train = zeros(length(lambda_vec), 1);
	error_val = zeros(length(lambda_vec), 1);
	
	for i = 1:length(lambda_vec)
			lambda = lambda_vec(i)
			[nn_params,cost] = trainNN(input_layer_size, ...
									hidden_layer_size, ...
									num_labels, ...
									options, ...
									X, y, lambda);
			
			error_train(i) = nnCostFunction(nn_params, ...
                                   input_layer_size, ...
                                   hidden_layer_size, ...
                                   num_labels, ...
                                   X, y, 0);
			error_val(i) = nnCostFunction(nn_params, ...
                                   input_layer_size, ...
                                   hidden_layer_size, ...
                                   num_labels, ...
                                   Xval, yval, 0);
	end
end
